In [1]:
import numpy as np

In [2]:
var=np.zeros(10)
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [4]:
var=np.ones(10)
var

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [6]:
var=np.ones(10)
var*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [11]:
var=np.arange(10,51)
var

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49, 50])

In [12]:
var=np.arange(10,51,2)
var

array([10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42,
       44, 46, 48, 50])

In [17]:
var=np.arange(9)
var.reshape(3,3)



array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [19]:
var=np.identity(3)
var

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [25]:
var=np.random.uniform(0,1)
var

0.8358167971198165

In [41]:
n=np.random.normal(size=25)
n

array([-0.37107494, -0.29362613,  0.62479329, -0.54110009, -0.70434494,
       -0.45908302,  1.60391597, -0.43749233,  0.08401738,  1.11106072,
        0.51906187, -0.36882585, -0.79609314, -0.98874328, -0.16949821,
       -0.28803411, -0.54474272,  0.61963589, -0.42286311, -0.81135726,
       -0.6504934 , -0.22247795, -0.38320659, -0.25132232, -0.32488277])

In [42]:
n=np.linspace(0,1,100).reshape(10,10)
n


array([[0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
        0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909],
       [0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
        0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919],
       [0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
        0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929],
       [0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
        0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939],
       [0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
        0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949],
       [0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
        0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ],
       [0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
        0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ],
       [0.70707071, 0.71717172, 0.7272727

In [43]:
n=np.linspace(0,1,20)
n

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [54]:
mat=np.arange(1,26).reshape(5,5)
mat

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [57]:
n=mat[2:5,1:5]
n

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [58]:
n=mat[3,4]
n

20

In [65]:
n=mat[0:3,1]
n

array([ 2,  7, 12])

In [66]:
n=mat[4]
n

array([21, 22, 23, 24, 25])

In [67]:
n=mat[3:5,0:5]
n

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [68]:
n=mat.sum()
n

325

In [70]:

n=np.std(mat)
n

7.211102550927978

In [73]:
n=mat.sum(axis=0)
n

array([55, 60, 65, 70, 75])